---
abstract: 'Expand range-like strings'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
build_requires:
  Test::More: '0'
  version: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.143240'
keywords:
  - text
  - string
  - range
  - expand
  - permute
  - glob
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-Range-Expand
provides:
  String::Range::Expand:
    file: lib/String/Range/Expand.pm
    version: v1.0.1
resources:
  bugtracker: https://github.com/mithun/perl-string-range-expand/issues
  homepage: https://github.com/mithun/perl-string-range-expand
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mithun/perl-string-range-expand.git
version: v1.0.1
