---
abstract: 'Expand range-like strings'
author:
  - 'Mithun Ayachit <mithun@cpan.org>'
build_requires:
  Test::More: 0
  version: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
keywords:
  - text
  - string
  - range
  - expand
  - permute
  - glob
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Range-Expand
provides:
  String::Range::Expand:
    file: lib/String/Range/Expand.pm
    version: 0.01
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=String-Range-Expand
  homepage: https://github.com/mithun/perl-string-range-expand
  license: http://dev.perl.org/licenses/
  repository: git://github.com/mithun/perl-string-range-expand.git
version: 0.01
